version: "2"
services:
    web:
        extends:
            file: ./services/web/nginx.yml
            service: web
        container_name: web
        environment:
            NGINX_HOST: test.local
            NGINX_PORT: 80
        links:
             - app
    db:
        extends:
            file: ./services/db/mysql.yml
            service: db
        container_name: db
        volumes:
            - .data/db:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_USER: s_user
            MYSQL_PASSEORD: password
    app:
        extends:
            file: ./services/app/php.yml
            service: app
        container_name: app
        links:
             - db


