version: "2"
services:
    web:
        extends:
            file: ./services/web/nginx.yml
            service: web
        container_name: web
        environment:
            NGINX_HOST: test.local
            NGINX_PORT: 80
        #    app:
        #        extends: ./services/app/php
        #        container_name: app
 
    db:
        extends:
            file: ./services/db/mysql.yml
            service: db
        container_name: db
        volumes:
            - .data/db:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_USER: s_user
            MYSQL_PASSEORD: password






