version: "2"

volumes:
    db:
        driver: 'local'

services:
    web:
        extends:
            file: ./web/nginx.yml
            service: web
        container_name: web
        links:
            - app
            - log_collector
        logging:
            driver: "fluentd"
            options:
                fluentd-address: "localhost:24224"
                tag: "web"
        depends_on:
            - app
            - log_collector

              #    db:
              #        extends:
              #            file: ./db/mysql.yml
              #            service: db
              #        container_name: db
              #        environment:
              #            MYSQL_ROOT_PASSWORD: password
              #            MYSQL_USER: s_user
              #            MYSQL_PASSEORD: password

    app:
        extends:
            file: ./app/php.yml
            service: app
        container_name: app
        links:
            - log_collector
        #     - db
        logging:
            driver: "fluentd"
            options:
                fluentd-address: "localhost:24224"
                tag: "app"
    log_collector:
        extends:
            file: ./log_collector/fluentd.yml
            service: log_collector
        container_name: log_collector
        volumes:
            - ./logs:/fluentd/log
