version: "2"
services:
    app:
        build: php
        volumes:
              #            - ./php/www.conf:/usr/local/etc/php-fpm.d/www.conf
            - ./php/xdebug_section.ini:/usr/local/etc/php/conf.d/xdebug_section.ini
            - ./php/:/var/www/html
